---
exclude_paths:
  - /github/workspace/.git/
  - /github/workspace/.github/
  - /github/workspace/.vagrant/
  - /github/workspace/.venv/
  - /github/workspace/.idea/
  - /github/workspace/.vscode/
  - /github/workspace/docs/
  - "super-linter"
use_default_rules: true
mock_modules:
  - community.general.lvol
verbosity: 1
skip_list:
  - yaml
  - name[casing]
  - name[template]
kinds:
  - inventory: "**/{inventory,inventories}/**/*.{yml,yaml}"
offline: true
