name: Lint Code Base
on:
  pull_request:
    branches: [main]

jobs:
  call-lint-workflow:
    uses: "riege/code-quality/.github/workflows/super-linter.yml@main"
    with:
      ANSIBLE_DIRECTORY: /dev/null
