---
name: Reusable super-linter workflow

on:
  workflow_call:
    inputs:
      CODEQUALITY_PATH:
        required: false
        type: string
        default: "super-linter"
        description: "Path name for the code-quality sources."
      CODEQUALITY_REF:
        required: false
        type: string
        default: "main"
        description: "Reference of the code-quality repo to use."
      ANSIBLE_DIRECTORY:
        required: false
        type: string
        default: "/ansible"
        description: >
          "Flag to set the root directory for Ansible file location(s),
          relative to DEFAULT_WORKSPACE. Set to . to use the top-level of
          the DEFAULT_WORKSPACE."
      VALIDATE_ALL_CODEBASE:
        required: false
        type: boolean
        default: false
        description: >
          "Will parse the entire repository and find all files to validate
          across all types. NOTE: When set to false, only new or edited files
          will be parsed for validation."

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Checkout code-quality Code
        uses: actions/checkout@v5
        with:
          repository: riege/code-quality
          path: ${{ inputs.CODEQUALITY_PATH }}
          ref: ${{ inputs.CODEQUALITY_REF }}

      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          ANSIBLE_CONFIG_FILE: ansible/.ansible-lint.yml
          ANSIBLE_DIRECTORY: ${{ inputs.ANSIBLE_DIRECTORY }}
          CHECKOV_FILE_NAME: checkov/.checkov.yaml
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ github.token }}
          JAVA_FILE_NAME: java/checkstyle/checkstyle.xml
          KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas
          LINTER_RULES_PATH: "${{ inputs.CODEQUALITY_PATH }}/"
          MARKDOWN_CONFIG_FILE: markdown/.markdown-lint.yml
          VALIDATE_ALL_CODEBASE: "${{ inputs.VALIDATE_ALL_CODEBASE }}"
          VALIDATE_JSCPD: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          YAML_CONFIG_FILE: yaml/.yaml-lint.yml
          TERRAFORM_TFLINT_CONFIG_FILE: terraform/.tflint.hcl
          SQLFLUFF_CONFIG_FILE: sqlfluff/.sqlfluff-lint
