---
name: Reusable super-linter workflow

on:
  workflow_call:
    inputs:
      CODEQUALITY_PATH:
        required: false
        type: string
        default: "super-linter"
        description: "Path name for the code-quality sources."
      CODEQUALITY_REF:
        required: false
        type: string
        default: "main"
        description: "Reference of the code-quality repo to use."
      ANSIBLE_DIRECTORY:
        required: false
        type: string
        default: "/ansible"
        description: >
          "Flag to set the root directory for Ansible file location(s),
          relative to DEFAULT_WORKSPACE. Set to . to use the top-level of
          the DEFAULT_WORKSPACE."
      FILTER_REGEX_EXCLUDE:
        required: false
        type: string
        default: ""
        description: >
          "If you need to exclude some files from linting, you can use this.
          Do not lint sql files: FILTER_REGEX_EXCLUDE: .*.sql
          Do not lint files inside test folder: FILTER_REGEX_EXCLUDE: .*test/.*
          Do not lint JavaScript files inside test folder: FILTER_REGEX_EXCLUDE: .*test/.*.js"

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout code-quality Code
        uses: actions/checkout@v2
        with:
          repository: riege/code-quality
          path: ${{ inputs.CODEQUALITY_PATH }}
          ref: ${{ inputs.CODEQUALITY_REF }}

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          ANSIBLE_CONFIG_FILE: ansible/.ansible-lint.yml
          ANSIBLE_DIRECTORY: ${{ inputs.ANSIBLE_DIRECTORY }}
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: "${{ inputs.FILTER_REGEX_EXCLUDE }}"
          GITHUB_TOKEN: ${{ github.token }}
          JAVA_FILE_NAME: java/checkstyle/checkstyle.xml
          KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas
          LINTER_RULES_PATH: "${{ inputs.CODEQUALITY_PATH }}/"
          MARKDOWN_CONFIG_FILE: markdown/.markdown-lint.yml
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_NATURAL_LANGUAGE: false
          YAML_CONFIG_FILE: yaml/.yaml-lint.yml
