---
name: Reusable super-linter workflow

on:
  workflow_call:
    inputs:
      ANSIBLE_DIRECTORY:
        required: false
        type: string
        default: "/ansible"
        description: >
          "Flag to set the root directory for Ansible file location(s),
          relative to DEFAULT_WORKSPACE. Set to . to use the top-level of
          the DEFAULT_WORKSPACE."

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_DIRECTORY: ${{ inputs.ANSIBLE_DIRECTORY }}
          VALIDATE_JSCPD: false
          VALIDATE_NATURAL_LANGUAGE: false
